// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjucdyyuowpebzbuixcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdWNkeXl1b3dwZWJ6YnVpeGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDc1MDcsImV4cCI6MjA2MDI4MzUwN30.sRGFEU2wgPArALac085pLDXO6oqwOFWDvOxr2EAdJ3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);